application: csgwebeditor
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: index.html
  upload: index.html
- url: /index.html
  static_files: index.html
  upload: index.html
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: favicon.ico
- url: /js/
  static_dir: js/
- url: /less/
  static_dir: less/
